spring:
  datasource:
    url: jdbc:mysql://localhost:3306/onlinecourse_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: false

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
springdoc:
  api-docs:
    path: /v3/api-docs
app:
  jwt-secret: ${JWT_SECRET}
app-jwt-expiration-milliseconds: 604800000
